### PR TITLE
SSO authentication between LDAP and Wordpress.

### PR DESCRIPTION
**Pull request by estevao90**
Was added a new functionality: SSO (Single Sign-on) between LDAP and Wordpress. The indenting of the code was revised, too.

### CODE REVIEW

**Comment by JayMaree** [comment]
Does it work for IIS?

**Comment by estevao90** [comment]
I think so. You just have to enable the windows authentication on IIS.

**Comment by clifgriffin** [comment]
Can you explain in detail how this works and what requirements it has? 

Also, what impact will it have on sites that do not use SSO?

**Comment by estevao90** [comment]
The SSO (Single Sign-on) is very useful for Intranet implementation, in which it is desirable that the user's access credentials be taken advantage of in the Intranet, without the need for a login, if the user has already done in workstation. 

This works in conjunction Apache protected directories configuration. The user must to follow the instructions described in [https://github.com/MP-ES/simple-ldap-login/blob/master/ssoCentOS.md](url) to CentOS or [https://github.com/MP-ES/simple-ldap-login/blob/master/ssoDebian.md](url) to Debian/Ubuntu to configure the SSO between the Workstation and Apache. For IIS, it's enough to enable the windows authentication.

After this initial setup, it is time to integrate with Wordpress. The plugin checks the authenticated user by checking the $ _SERVER ['REMOTE_USER'] variable, and make the login. To do this, it uses a LDAP user to bind and search user data.

A new configuration tab (SSO) has been added, in which configurations can be made.
sll

If a site does not use SSO, it's enough uncheck the *Enable SSO* option. Anyway, the default for *Enable SSO* is unchecked.

**Comment by clifgriffin** [comment]
You've obviously put a lot of time and thought into this! 

Since the feature is disabled by default, I'm going to review the code and then plan on merging this into the next version.

**Comment by jpuck** [comment]
Does it fallback to login form if the client device isn't a domain workstation, such as a phone or other personal device?

**Comment by estevao90** [comment]
@jpuck, yes. If credential negotiation fails, Apache will request login and password.

**Comment by estevao90** [comment]
1. It's not necessary to check permissions in Simple-LDAP-Login-Admin.php. WP should handle this automatically in the add_options_page() call. - **OK**
2. Is it necessary to include netbeans project files? This seems like a local dependency that should be gitignored.
**I think that this files can help others developers. I created a script to build the zip (buildZipWP.sh) for Wordpress that remove these unnecessary files.**
3. Is it necessary to include the RPM files? Who owns these and where do they come from? I'd rather link to an external source for these.
**Include this file can help people that don't have familiarity to compile the source code of the module. I put in the documentation the url to the module source code.**
4. Can you translate the SSO instructions into English? - **OK**
5. Similarly, can you translate your comments into English? - **OK**

Anyway, If you find it better to remove the files, I can remove.

**Comment by clifgriffin** [comment]
@estevao90 Let's remove the RPM and add a link in the instructions.

Also, make sure the build script is in a separate directory that starts with a period. 

Ie, 
simple-ldap-login/.assets/buildZipWP.sh

Also, it may be helpful to rename the script so that it is more clear what it does.

**Comment by estevao90** [comment]
Ok. Done.

**Pull request merged**
